version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: organisation_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: organisation_db
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3308:3306'

volumes:
  my-db: